spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=Your password here

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Use port 8081 to avoid conflicts
server.port=8081
jwt.secret=mysecretkeymysecretkeymysecretkey123456789
jwt.expiration=3600000
